---
- hosts: localhost
  vars:
    -ansible_python_interpreter: /usr/bin/python
     key_name: **********
     instance_type: t2.micro
     image: **********
     subnet_id: **********
     aws_access_key: **********
     aws_secret_key: *****************
